-- Seed file: 100 common cocktails
-- Usage:
--   mysql -u root -p barcraft < db/seed_common_drinks.sql

USE barcraft;

START TRANSACTION;

CREATE TEMPORARY TABLE tmp_seed_drinks (
  name VARCHAR(120) NOT NULL PRIMARY KEY,
  description VARCHAR(255) NULL,
  instructions TEXT NOT NULL,
  quote TEXT NULL,
  is_classic TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB;

CREATE TEMPORARY TABLE tmp_seed_drink_ingredients (
  drink_name VARCHAR(120) NOT NULL,
  ingredient_name VARCHAR(120) NOT NULL,
  amount VARCHAR(80) NULL,
  PRIMARY KEY (drink_name, ingredient_name)
) ENGINE=InnoDB;

INSERT INTO tmp_seed_drinks (name, description, instructions, quote, is_classic) VALUES
('Margarita', 'Classic tequila sour.', 'Shake with ice and strain into a chilled glass.', NULL, 1),
('Tommy''s Margarita', 'Agave-based margarita variation.', 'Shake with ice and strain into a chilled glass.', NULL, 1),
('Paloma', 'Refreshing tequila and grapefruit highball.', 'Build over ice and top with soda.', NULL, 1),
('Tequila Sunrise', 'Fruity tequila highball.', 'Build over ice and add grenadine last.', NULL, 1),
('El Diablo', 'Tequila with cassis and ginger beer.', 'Build over ice and stir gently.', NULL, 1),
('Daiquiri', 'Rum sour served up.', 'Shake with ice and strain into a coupe.', NULL, 1),
('Mojito', 'Minty rum highball.', 'Muddle mint, add ingredients, top with soda and ice.', NULL, 1),
('Caipirinha', 'Brazilian lime and cachaca classic.', 'Muddle lime and sugar, add cachaca and crushed ice.', NULL, 1),
('Caipiroska', 'Vodka version of Caipirinha.', 'Muddle lime and sugar, add vodka and crushed ice.', NULL, 1),
('Cuba Libre', 'Rum and cola with lime.', 'Build over ice and stir.', NULL, 1),
('Dark and Stormy', 'Dark rum and ginger beer highball.', 'Build over ice and float dark rum.', NULL, 1),
('Mai Tai', 'Tropical rum classic.', 'Shake with ice and strain over fresh ice.', NULL, 1),
('Pina Colada', 'Creamy pineapple rum cocktail.', 'Blend with ice until smooth.', NULL, 1),
('Zombie', 'Strong multi-rum tiki cocktail.', 'Shake with ice and serve over crushed ice.', NULL, 1),
('Painkiller', 'Creamy tropical rum drink.', 'Shake and serve over crushed ice.', NULL, 1),
('Hurricane', 'Fruity New Orleans rum cocktail.', 'Shake with ice and strain over fresh ice.', NULL, 1),
('Planter''s Punch', 'Rich rum punch.', 'Shake and serve over ice.', NULL, 1),
('Rum Punch', 'Classic party rum punch.', 'Shake and serve over ice.', NULL, 1),
('Old Fashioned', 'Spirit-forward whiskey cocktail.', 'Stir with ice and strain over a large cube.', NULL, 1),
('Manhattan', 'Whiskey and vermouth classic.', 'Stir with ice and strain into a coupe.', NULL, 1),
('Perfect Manhattan', 'Manhattan with split vermouth.', 'Stir with ice and strain into a coupe.', NULL, 1),
('Whiskey Sour', 'Balanced whiskey sour.', 'Shake with ice and strain over fresh ice.', NULL, 1),
('Mint Julep', 'Bourbon and mint over crushed ice.', 'Muddle mint lightly and pack with crushed ice.', NULL, 1),
('Sazerac', 'New Orleans aromatic classic.', 'Stir and strain into an absinthe-rinsed glass.', NULL, 1),
('Vieux Carre', 'Complex New Orleans whiskey cocktail.', 'Stir with ice and strain over fresh ice.', NULL, 1),
('Boulevardier', 'Whiskey Negroni variation.', 'Stir with ice and strain over fresh ice.', NULL, 1),
('Penicillin', 'Smoky and spicy modern classic.', 'Shake base and float smoky whisky on top.', NULL, 1),
('Paper Plane', 'Modern equal-parts bourbon cocktail.', 'Shake with ice and strain into a coupe.', NULL, 1),
('Gold Rush', 'Bourbon sour with honey.', 'Shake with ice and strain over fresh ice.', NULL, 1),
('Rusty Nail', 'Scotch and Drambuie sipper.', 'Stir over ice in a rocks glass.', NULL, 1),
('Rob Roy', 'Scotch Manhattan variation.', 'Stir with ice and strain into a coupe.', NULL, 1),
('Godfather', 'Simple scotch and amaretto.', 'Build over ice and stir.', NULL, 1),
('Godmother', 'Vodka and amaretto.', 'Build over ice and stir.', NULL, 1),
('Highball', 'Simple whisky and soda.', 'Build in a tall glass with ice.', NULL, 1),
('Gin and Tonic', 'Crisp gin highball.', 'Build over ice and garnish with lime.', NULL, 1),
('Tom Collins', 'Gin sour lengthened with soda.', 'Shake first three, top with soda.', NULL, 1),
('Gin Fizz', 'Light and foamy gin sour.', 'Shake and top with soda.', NULL, 1),
('French 75', 'Sparkling gin sour.', 'Shake base, strain, and top with sparkling wine.', NULL, 1),
('Negroni', 'Bitter-sweet Italian classic.', 'Stir with ice and strain over a large cube.', NULL, 1),
('Americano', 'Low-ABV Campari highball.', 'Build over ice and top with soda.', NULL, 1),
('Martini', 'Iconic gin and vermouth cocktail.', 'Stir with ice and strain into a chilled glass.', NULL, 1),
('Vodka Martini', 'Clean vodka martini.', 'Stir with ice and strain into a chilled glass.', NULL, 1),
('Dirty Martini', 'Martini with olive brine.', 'Stir with ice and strain into a chilled glass.', NULL, 1),
('Gibson', 'Martini garnished with onion.', 'Stir with ice and strain into a chilled glass.', NULL, 1),
('Gimlet', 'Gin and lime sour.', 'Shake with ice and strain into a chilled glass.', NULL, 1),
('Southside', 'Minty gin sour.', 'Shake with ice and fine strain into a coupe.', NULL, 1),
('Bee''s Knees', 'Honey-sweetened gin sour.', 'Shake with ice and strain into a coupe.', NULL, 1),
('Last Word', 'Herbal equal-parts classic.', 'Shake with ice and strain into a coupe.', NULL, 1),
('Aviation', 'Floral gin sour.', 'Shake with ice and strain into a coupe.', NULL, 1),
('Corpse Reviver No. 2', 'Bright pre-dinner classic.', 'Shake with ice and strain into an absinthe-rinsed coupe.', NULL, 1),
('Clover Club', 'Silky raspberry gin sour.', 'Dry shake then shake with ice and strain.', NULL, 1),
('Bramble', 'Gin sour with berry liqueur.', 'Shake base and drizzle liqueur over crushed ice.', NULL, 1),
('Singapore Sling', 'Complex tropical gin cocktail.', 'Shake with ice and strain over fresh ice.', NULL, 1),
('White Lady', 'Elegant gin sidecar style drink.', 'Shake with ice and strain into a coupe.', NULL, 1),
('Ramos Gin Fizz', 'Creamy citrus gin fizz.', 'Shake hard and top with soda.', NULL, 1),
('Sidecar', 'Brandy sour classic.', 'Shake with ice and strain into a coupe.', NULL, 1),
('French Connection', 'Cognac and amaretto.', 'Build over ice and stir.', NULL, 1),
('Brandy Alexander', 'Creamy dessert cocktail.', 'Shake with ice and strain into a coupe.', NULL, 1),
('Alexander', 'Gin-based dessert cocktail.', 'Shake with ice and strain into a coupe.', NULL, 1),
('Pisco Sour', 'Foamy Peruvian sour.', 'Dry shake then shake with ice and strain.', NULL, 1),
('Cosmopolitan', 'Citrus vodka classic.', 'Shake with ice and strain into a coupe.', NULL, 1),
('Moscow Mule', 'Vodka ginger highball.', 'Build over ice and stir gently.', NULL, 1),
('Kentucky Mule', 'Bourbon mule variation.', 'Build over ice and stir gently.', NULL, 1),
('Irish Mule', 'Irish whiskey mule variation.', 'Build over ice and stir gently.', NULL, 1),
('Espresso Martini', 'Vodka and coffee cocktail.', 'Shake hard with ice and strain into a coupe.', NULL, 1),
('White Russian', 'Creamy vodka coffee cocktail.', 'Build over ice and float cream.', NULL, 1),
('Black Russian', 'Vodka and coffee liqueur.', 'Build over ice and stir.', NULL, 1),
('Bloody Mary', 'Savory vodka brunch classic.', 'Roll with ice and serve in a tall glass.', NULL, 1),
('Screwdriver', 'Vodka and orange juice.', 'Build over ice and stir.', NULL, 1),
('Greyhound', 'Vodka and grapefruit juice.', 'Build over ice and stir.', NULL, 1),
('Salty Dog', 'Salt-rimmed grapefruit highball.', 'Build over ice in a salt-rimmed glass.', NULL, 1),
('Cape Codder', 'Vodka cranberry highball.', 'Build over ice and stir.', NULL, 1),
('Sea Breeze', 'Cranberry and grapefruit cooler.', 'Build over ice and stir.', NULL, 1),
('Bay Breeze', 'Cranberry and pineapple cooler.', 'Build over ice and stir.', NULL, 1),
('Sex on the Beach', 'Fruity vodka highball.', 'Build over ice and stir.', NULL, 1),
('Woo Woo', 'Vodka, peach, and cranberry.', 'Build over ice and stir.', NULL, 1),
('Kamikaze', 'Vodka citrus shooter.', 'Shake with ice and strain.', NULL, 1),
('Lemon Drop Martini', 'Sweet-tart vodka martini.', 'Shake with ice and strain into a chilled glass.', NULL, 1),
('French Martini', 'Vodka, raspberry, and pineapple.', 'Shake with ice and strain into a coupe.', NULL, 1),
('Appletini', 'Apple-flavored vodka martini.', 'Shake with ice and strain into a chilled glass.', NULL, 1),
('Midori Sour', 'Melon citrus sour.', 'Shake with ice and top with soda.', NULL, 1),
('Blue Lagoon', 'Blue citrus vodka drink.', 'Build over ice and stir.', NULL, 1),
('Long Island Iced Tea', 'Strong mixed-spirit highball.', 'Shake base with ice, strain over fresh ice, top with cola.', NULL, 1),
('Bellini', 'Sparkling peach cocktail.', 'Build in a flute and stir lightly.', NULL, 1),
('Mimosa', 'Sparkling orange brunch classic.', 'Build in a flute and stir lightly.', NULL, 1),
('Aperol Spritz', 'Bittersweet sparkling aperitif.', 'Build over ice and stir gently.', NULL, 1),
('Kir', 'White wine and cassis aperitif.', 'Build in a wine glass and stir lightly.', NULL, 1),
('Kir Royale', 'Champagne and cassis aperitif.', 'Build in a flute and stir lightly.', NULL, 1),
('Negroni Sbagliato', 'Negroni with sparkling wine.', 'Build over ice and stir gently.', NULL, 1),
('Black Manhattan', 'Manhattan with amaro.', 'Stir with ice and strain into a coupe.', NULL, 1),
('Irish Coffee', 'Warm coffee and whiskey cocktail.', 'Build in a warm glass and float cream.', NULL, 1),
('Hot Toddy', 'Warm whiskey and honey drink.', 'Build in a warm mug and stir.', NULL, 1),
('Amaretto Sour', 'Nutty almond sour.', 'Shake with ice and strain over fresh ice.', NULL, 1),
('Stinger', 'Cognac and mint digestif.', 'Stir with ice and strain into a chilled glass.', NULL, 1),
('Grasshopper', 'Mint-chocolate cream cocktail.', 'Shake with ice and strain into a chilled glass.', NULL, 1),
('Golden Dream', 'Creamy orange dessert cocktail.', 'Shake with ice and strain into a chilled glass.', NULL, 1),
('B-52', 'Layered coffee cream orange shot.', 'Layer ingredients carefully in a shot glass.', NULL, 1),
('Tuxedo', 'Aromatic martini variation.', 'Stir with ice and strain into a chilled glass.', NULL, 1),
('Martinez', 'Historic gin and vermouth cocktail.', 'Stir with ice and strain into a chilled glass.', NULL, 1),
('Bijou', 'Gin, vermouth, and chartreuse classic.', 'Stir with ice and strain into a chilled glass.', NULL, 1);

INSERT INTO tmp_seed_drink_ingredients (drink_name, ingredient_name, amount) VALUES
('Margarita', 'tequila blanco', '50 ml'),
('Margarita', 'triple sec', '25 ml'),
('Margarita', 'lime juice', '25 ml'),
('Tommy''s Margarita', 'tequila blanco', '60 ml'),
('Tommy''s Margarita', 'agave syrup', '20 ml'),
('Tommy''s Margarita', 'lime juice', '30 ml'),
('Paloma', 'tequila blanco', '50 ml'),
('Paloma', 'grapefruit soda', '100 ml'),
('Paloma', 'lime juice', '15 ml'),
('Tequila Sunrise', 'tequila blanco', '50 ml'),
('Tequila Sunrise', 'orange juice', '100 ml'),
('Tequila Sunrise', 'grenadine', '10 ml'),
('El Diablo', 'tequila blanco', '45 ml'),
('El Diablo', 'creme de cassis', '15 ml'),
('El Diablo', 'lime juice', '20 ml'),
('El Diablo', 'ginger beer', '90 ml'),
('Daiquiri', 'white rum', '60 ml'),
('Daiquiri', 'lime juice', '25 ml'),
('Daiquiri', 'simple syrup', '15 ml'),
('Mojito', 'white rum', '50 ml'),
('Mojito', 'lime juice', '25 ml'),
('Mojito', 'mint leaves', '10 leaves'),
('Mojito', 'sugar', '2 tsp'),
('Mojito', 'soda water', 'top'),
('Caipirinha', 'cachaca', '60 ml'),
('Caipirinha', 'lime', '1'),
('Caipirinha', 'sugar', '2 tsp'),
('Caipiroska', 'vodka', '60 ml'),
('Caipiroska', 'lime', '1'),
('Caipiroska', 'sugar', '2 tsp'),
('Cuba Libre', 'dark rum', '50 ml'),
('Cuba Libre', 'cola', '120 ml'),
('Cuba Libre', 'lime juice', '15 ml'),
('Dark and Stormy', 'dark rum', '50 ml'),
('Dark and Stormy', 'ginger beer', '120 ml'),
('Dark and Stormy', 'lime juice', '10 ml'),
('Mai Tai', 'white rum', '30 ml'),
('Mai Tai', 'dark rum', '30 ml'),
('Mai Tai', 'orange curacao', '15 ml'),
('Mai Tai', 'orgeat syrup', '15 ml'),
('Mai Tai', 'lime juice', '30 ml'),
('Pina Colada', 'white rum', '50 ml'),
('Pina Colada', 'pineapple juice', '90 ml'),
('Pina Colada', 'coconut cream', '30 ml'),
('Zombie', 'white rum', '30 ml'),
('Zombie', 'dark rum', '30 ml'),
('Zombie', 'overproof rum', '20 ml'),
('Zombie', 'lime juice', '20 ml'),
('Zombie', 'pineapple juice', '40 ml'),
('Zombie', 'passion fruit syrup', '20 ml'),
('Zombie', 'grenadine', '10 ml'),
('Painkiller', 'dark rum', '60 ml'),
('Painkiller', 'pineapple juice', '90 ml'),
('Painkiller', 'orange juice', '30 ml'),
('Painkiller', 'coconut cream', '30 ml'),
('Hurricane', 'light rum', '30 ml'),
('Hurricane', 'dark rum', '30 ml'),
('Hurricane', 'passion fruit syrup', '30 ml'),
('Hurricane', 'lemon juice', '20 ml'),
('Planter''s Punch', 'dark rum', '60 ml'),
('Planter''s Punch', 'lime juice', '25 ml'),
('Planter''s Punch', 'simple syrup', '20 ml'),
('Planter''s Punch', 'angostura bitters', '2 dashes'),
('Rum Punch', 'dark rum', '50 ml'),
('Rum Punch', 'orange juice', '60 ml'),
('Rum Punch', 'pineapple juice', '60 ml'),
('Rum Punch', 'lime juice', '15 ml'),
('Rum Punch', 'grenadine', '10 ml'),
('Old Fashioned', 'bourbon', '60 ml'),
('Old Fashioned', 'simple syrup', '7 ml'),
('Old Fashioned', 'angostura bitters', '2 dashes'),
('Manhattan', 'rye whiskey', '60 ml'),
('Manhattan', 'sweet vermouth', '30 ml'),
('Manhattan', 'angostura bitters', '2 dashes'),
('Perfect Manhattan', 'rye whiskey', '60 ml'),
('Perfect Manhattan', 'sweet vermouth', '15 ml'),
('Perfect Manhattan', 'dry vermouth', '15 ml'),
('Perfect Manhattan', 'angostura bitters', '2 dashes'),
('Whiskey Sour', 'bourbon', '60 ml'),
('Whiskey Sour', 'lemon juice', '25 ml'),
('Whiskey Sour', 'simple syrup', '20 ml'),
('Whiskey Sour', 'egg white', '1'),
('Mint Julep', 'bourbon', '60 ml'),
('Mint Julep', 'mint leaves', '8 leaves'),
('Mint Julep', 'simple syrup', '10 ml'),
('Sazerac', 'rye whiskey', '45 ml'),
('Sazerac', 'cognac', '15 ml'),
('Sazerac', 'absinthe', 'rinse'),
('Sazerac', 'sugar cube', '1'),
('Sazerac', 'peychaud bitters', '3 dashes'),
('Vieux Carre', 'rye whiskey', '30 ml'),
('Vieux Carre', 'cognac', '30 ml'),
('Vieux Carre', 'sweet vermouth', '30 ml'),
('Vieux Carre', 'benedictine', '5 ml'),
('Vieux Carre', 'peychaud bitters', '2 dashes'),
('Boulevardier', 'bourbon', '30 ml'),
('Boulevardier', 'sweet vermouth', '30 ml'),
('Boulevardier', 'campari', '30 ml'),
('Penicillin', 'blended scotch', '60 ml'),
('Penicillin', 'islay scotch', '10 ml'),
('Penicillin', 'lemon juice', '25 ml'),
('Penicillin', 'honey ginger syrup', '20 ml'),
('Paper Plane', 'bourbon', '22 ml'),
('Paper Plane', 'aperol', '22 ml'),
('Paper Plane', 'amaro nonino', '22 ml'),
('Paper Plane', 'lemon juice', '22 ml'),
('Gold Rush', 'bourbon', '60 ml'),
('Gold Rush', 'honey syrup', '20 ml'),
('Gold Rush', 'lemon juice', '25 ml'),
('Rusty Nail', 'scotch whisky', '45 ml'),
('Rusty Nail', 'drambuie', '25 ml'),
('Rob Roy', 'scotch whisky', '60 ml'),
('Rob Roy', 'sweet vermouth', '30 ml'),
('Rob Roy', 'angostura bitters', '2 dashes'),
('Godfather', 'scotch whisky', '45 ml'),
('Godfather', 'amaretto', '25 ml'),
('Godmother', 'vodka', '45 ml'),
('Godmother', 'amaretto', '25 ml'),
('Highball', 'whisky', '45 ml'),
('Highball', 'soda water', '120 ml'),
('Gin and Tonic', 'gin', '50 ml'),
('Gin and Tonic', 'tonic water', '120 ml'),
('Gin and Tonic', 'lime wedge', '1'),
('Tom Collins', 'gin', '45 ml'),
('Tom Collins', 'lemon juice', '30 ml'),
('Tom Collins', 'simple syrup', '15 ml'),
('Tom Collins', 'soda water', 'top'),
('Gin Fizz', 'gin', '45 ml'),
('Gin Fizz', 'lemon juice', '30 ml'),
('Gin Fizz', 'simple syrup', '15 ml'),
('Gin Fizz', 'soda water', 'top'),
('French 75', 'gin', '30 ml'),
('French 75', 'lemon juice', '15 ml'),
('French 75', 'simple syrup', '15 ml'),
('French 75', 'champagne', '60 ml'),
('Negroni', 'gin', '30 ml'),
('Negroni', 'campari', '30 ml'),
('Negroni', 'sweet vermouth', '30 ml'),
('Americano', 'campari', '30 ml'),
('Americano', 'sweet vermouth', '30 ml'),
('Americano', 'soda water', '60 ml'),
('Martini', 'gin', '60 ml'),
('Martini', 'dry vermouth', '10 ml'),
('Vodka Martini', 'vodka', '60 ml'),
('Vodka Martini', 'dry vermouth', '10 ml'),
('Dirty Martini', 'gin', '55 ml'),
('Dirty Martini', 'dry vermouth', '10 ml'),
('Dirty Martini', 'olive brine', '10 ml'),
('Gibson', 'gin', '60 ml'),
('Gibson', 'dry vermouth', '10 ml'),
('Gibson', 'cocktail onion', '1'),
('Gimlet', 'gin', '60 ml'),
('Gimlet', 'lime juice', '25 ml'),
('Gimlet', 'simple syrup', '10 ml'),
('Southside', 'gin', '60 ml'),
('Southside', 'lime juice', '25 ml'),
('Southside', 'simple syrup', '15 ml'),
('Southside', 'mint leaves', '8 leaves'),
('Bee''s Knees', 'gin', '60 ml'),
('Bee''s Knees', 'honey syrup', '20 ml'),
('Bee''s Knees', 'lemon juice', '25 ml'),
('Last Word', 'gin', '22 ml'),
('Last Word', 'green chartreuse', '22 ml'),
('Last Word', 'maraschino liqueur', '22 ml'),
('Last Word', 'lime juice', '22 ml'),
('Aviation', 'gin', '45 ml'),
('Aviation', 'maraschino liqueur', '15 ml'),
('Aviation', 'creme de violette', '5 ml'),
('Aviation', 'lemon juice', '15 ml'),
('Corpse Reviver No. 2', 'gin', '22 ml'),
('Corpse Reviver No. 2', 'cointreau', '22 ml'),
('Corpse Reviver No. 2', 'lillet blanc', '22 ml'),
('Corpse Reviver No. 2', 'lemon juice', '22 ml'),
('Corpse Reviver No. 2', 'absinthe', 'rinse'),
('Clover Club', 'gin', '45 ml'),
('Clover Club', 'raspberry syrup', '15 ml'),
('Clover Club', 'lemon juice', '20 ml'),
('Clover Club', 'egg white', '1'),
('Bramble', 'gin', '50 ml'),
('Bramble', 'lemon juice', '25 ml'),
('Bramble', 'simple syrup', '15 ml'),
('Bramble', 'creme de mure', '15 ml'),
('Singapore Sling', 'gin', '30 ml'),
('Singapore Sling', 'cherry liqueur', '15 ml'),
('Singapore Sling', 'benedictine', '7 ml'),
('Singapore Sling', 'cointreau', '7 ml'),
('Singapore Sling', 'pineapple juice', '120 ml'),
('Singapore Sling', 'lime juice', '15 ml'),
('Singapore Sling', 'grenadine', '10 ml'),
('White Lady', 'gin', '45 ml'),
('White Lady', 'cointreau', '22 ml'),
('White Lady', 'lemon juice', '22 ml'),
('Ramos Gin Fizz', 'gin', '45 ml'),
('Ramos Gin Fizz', 'lemon juice', '15 ml'),
('Ramos Gin Fizz', 'lime juice', '15 ml'),
('Ramos Gin Fizz', 'simple syrup', '15 ml'),
('Ramos Gin Fizz', 'cream', '30 ml'),
('Ramos Gin Fizz', 'egg white', '1'),
('Ramos Gin Fizz', 'orange flower water', '2 drops'),
('Ramos Gin Fizz', 'soda water', 'top'),
('Sidecar', 'cognac', '50 ml'),
('Sidecar', 'cointreau', '25 ml'),
('Sidecar', 'lemon juice', '25 ml'),
('French Connection', 'cognac', '35 ml'),
('French Connection', 'amaretto', '35 ml'),
('Brandy Alexander', 'brandy', '30 ml'),
('Brandy Alexander', 'creme de cacao', '30 ml'),
('Brandy Alexander', 'cream', '30 ml'),
('Alexander', 'gin', '30 ml'),
('Alexander', 'creme de cacao', '30 ml'),
('Alexander', 'cream', '30 ml'),
('Pisco Sour', 'pisco', '60 ml'),
('Pisco Sour', 'lime juice', '30 ml'),
('Pisco Sour', 'simple syrup', '20 ml'),
('Pisco Sour', 'egg white', '1'),
('Cosmopolitan', 'vodka citron', '40 ml'),
('Cosmopolitan', 'cointreau', '20 ml'),
('Cosmopolitan', 'cranberry juice', '30 ml'),
('Cosmopolitan', 'lime juice', '15 ml'),
('Moscow Mule', 'vodka', '50 ml'),
('Moscow Mule', 'lime juice', '20 ml'),
('Moscow Mule', 'ginger beer', '120 ml'),
('Kentucky Mule', 'bourbon', '50 ml'),
('Kentucky Mule', 'lime juice', '20 ml'),
('Kentucky Mule', 'ginger beer', '120 ml'),
('Irish Mule', 'irish whiskey', '50 ml'),
('Irish Mule', 'lime juice', '20 ml'),
('Irish Mule', 'ginger beer', '120 ml'),
('Espresso Martini', 'vodka', '50 ml'),
('Espresso Martini', 'coffee liqueur', '25 ml'),
('Espresso Martini', 'espresso', '30 ml'),
('Espresso Martini', 'simple syrup', '10 ml'),
('White Russian', 'vodka', '50 ml'),
('White Russian', 'coffee liqueur', '25 ml'),
('White Russian', 'cream', '25 ml'),
('Black Russian', 'vodka', '50 ml'),
('Black Russian', 'coffee liqueur', '25 ml'),
('Bloody Mary', 'vodka', '45 ml'),
('Bloody Mary', 'tomato juice', '90 ml'),
('Bloody Mary', 'lemon juice', '15 ml'),
('Bloody Mary', 'worcestershire sauce', '2 dashes'),
('Bloody Mary', 'tabasco', '2 dashes'),
('Screwdriver', 'vodka', '50 ml'),
('Screwdriver', 'orange juice', '100 ml'),
('Greyhound', 'vodka', '50 ml'),
('Greyhound', 'grapefruit juice', '100 ml'),
('Salty Dog', 'gin', '50 ml'),
('Salty Dog', 'grapefruit juice', '100 ml'),
('Salty Dog', 'salt', 'rim'),
('Cape Codder', 'vodka', '50 ml'),
('Cape Codder', 'cranberry juice', '120 ml'),
('Cape Codder', 'lime juice', '10 ml'),
('Sea Breeze', 'vodka', '40 ml'),
('Sea Breeze', 'cranberry juice', '90 ml'),
('Sea Breeze', 'grapefruit juice', '45 ml'),
('Bay Breeze', 'vodka', '40 ml'),
('Bay Breeze', 'cranberry juice', '90 ml'),
('Bay Breeze', 'pineapple juice', '45 ml'),
('Sex on the Beach', 'vodka', '40 ml'),
('Sex on the Beach', 'peach schnapps', '20 ml'),
('Sex on the Beach', 'cranberry juice', '40 ml'),
('Sex on the Beach', 'orange juice', '40 ml'),
('Woo Woo', 'vodka', '40 ml'),
('Woo Woo', 'peach schnapps', '20 ml'),
('Woo Woo', 'cranberry juice', '80 ml'),
('Kamikaze', 'vodka', '30 ml'),
('Kamikaze', 'triple sec', '30 ml'),
('Kamikaze', 'lime juice', '30 ml'),
('Lemon Drop Martini', 'vodka', '45 ml'),
('Lemon Drop Martini', 'triple sec', '20 ml'),
('Lemon Drop Martini', 'lemon juice', '20 ml'),
('Lemon Drop Martini', 'simple syrup', '10 ml'),
('French Martini', 'vodka', '45 ml'),
('French Martini', 'chambord', '15 ml'),
('French Martini', 'pineapple juice', '45 ml'),
('Appletini', 'vodka', '45 ml'),
('Appletini', 'apple schnapps', '20 ml'),
('Appletini', 'lemon juice', '10 ml'),
('Midori Sour', 'midori', '30 ml'),
('Midori Sour', 'vodka', '30 ml'),
('Midori Sour', 'lemon juice', '30 ml'),
('Midori Sour', 'soda water', 'top'),
('Blue Lagoon', 'vodka', '45 ml'),
('Blue Lagoon', 'blue curacao', '20 ml'),
('Blue Lagoon', 'lemonade', '80 ml'),
('Long Island Iced Tea', 'vodka', '15 ml'),
('Long Island Iced Tea', 'gin', '15 ml'),
('Long Island Iced Tea', 'white rum', '15 ml'),
('Long Island Iced Tea', 'tequila blanco', '15 ml'),
('Long Island Iced Tea', 'triple sec', '15 ml'),
('Long Island Iced Tea', 'lemon juice', '25 ml'),
('Long Island Iced Tea', 'simple syrup', '15 ml'),
('Long Island Iced Tea', 'cola', 'top'),
('Bellini', 'prosecco', '90 ml'),
('Bellini', 'peach puree', '45 ml'),
('Mimosa', 'prosecco', '75 ml'),
('Mimosa', 'orange juice', '75 ml'),
('Aperol Spritz', 'aperol', '60 ml'),
('Aperol Spritz', 'prosecco', '90 ml'),
('Aperol Spritz', 'soda water', '30 ml'),
('Kir', 'dry white wine', '120 ml'),
('Kir', 'creme de cassis', '15 ml'),
('Kir Royale', 'champagne', '120 ml'),
('Kir Royale', 'creme de cassis', '15 ml'),
('Negroni Sbagliato', 'campari', '30 ml'),
('Negroni Sbagliato', 'sweet vermouth', '30 ml'),
('Negroni Sbagliato', 'prosecco', '30 ml'),
('Black Manhattan', 'rye whiskey', '60 ml'),
('Black Manhattan', 'amaro averna', '30 ml'),
('Black Manhattan', 'angostura bitters', '1 dash'),
('Black Manhattan', 'orange bitters', '1 dash'),
('Irish Coffee', 'irish whiskey', '45 ml'),
('Irish Coffee', 'hot coffee', '120 ml'),
('Irish Coffee', 'sugar', '2 tsp'),
('Irish Coffee', 'cream', 'float'),
('Hot Toddy', 'whiskey', '45 ml'),
('Hot Toddy', 'hot water', '120 ml'),
('Hot Toddy', 'honey', '1 tbsp'),
('Hot Toddy', 'lemon juice', '15 ml'),
('Amaretto Sour', 'amaretto', '45 ml'),
('Amaretto Sour', 'lemon juice', '30 ml'),
('Amaretto Sour', 'simple syrup', '10 ml'),
('Amaretto Sour', 'egg white', '1'),
('Stinger', 'cognac', '60 ml'),
('Stinger', 'white creme de menthe', '20 ml'),
('Grasshopper', 'green creme de menthe', '30 ml'),
('Grasshopper', 'white creme de cacao', '30 ml'),
('Grasshopper', 'cream', '30 ml'),
('Golden Dream', 'galliano', '20 ml'),
('Golden Dream', 'cointreau', '20 ml'),
('Golden Dream', 'orange juice', '20 ml'),
('Golden Dream', 'cream', '20 ml'),
('B-52', 'coffee liqueur', '20 ml'),
('B-52', 'irish cream liqueur', '20 ml'),
('B-52', 'orange liqueur', '20 ml'),
('Tuxedo', 'gin', '45 ml'),
('Tuxedo', 'dry vermouth', '45 ml'),
('Tuxedo', 'maraschino liqueur', '5 ml'),
('Tuxedo', 'absinthe', 'dash'),
('Tuxedo', 'orange bitters', '1 dash'),
('Martinez', 'gin', '45 ml'),
('Martinez', 'sweet vermouth', '45 ml'),
('Martinez', 'maraschino liqueur', '5 ml'),
('Martinez', 'orange bitters', '2 dashes'),
('Bijou', 'gin', '30 ml'),
('Bijou', 'sweet vermouth', '30 ml'),
('Bijou', 'green chartreuse', '30 ml'),
('Bijou', 'orange bitters', '1 dash');

INSERT INTO drinks (name, description, instructions, quote, is_classic)
SELECT t.name, t.description, t.instructions, t.quote, t.is_classic
FROM tmp_seed_drinks t
LEFT JOIN drinks d ON d.name = t.name
WHERE d.id IS NULL;

INSERT IGNORE INTO ingredients (name)
SELECT DISTINCT LOWER(TRIM(ingredient_name))
FROM tmp_seed_drink_ingredients;

INSERT IGNORE INTO drink_ingredients (drink_id, ingredient_id, amount)
SELECT d.id, i.id, t.amount
FROM tmp_seed_drink_ingredients t
JOIN drinks d ON d.name = t.drink_name
JOIN ingredients i ON i.name = LOWER(TRIM(t.ingredient_name));

COMMIT;
